# Site settings
title: Coding for Knuc(k)le Draggers
header-img: img/home-bg.png
email: william.l.kann@gmail.com
copyright_name: kanndide
description: > # this means to ignore newlines until "baseurl:"
  From discovering fire to learning how to program. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kanndide
learn_profile: kanndide
email_username: william.l.kann@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
